exports.HTTP_OK = 200;
exports.HTTP_CREATED = 201;
exports.HTTP_NO_CONTENT = 204;
exports.HTTP_BAD_REQUEST = 400;
exports.HTTP_UNATHORIZED = 401;
exports.HTTP_FORBIDDEN = 403;
exports.HTTP_NOT_FOUND = 404;
exports.HTTP_INTERNAL_SERVER_ERROR = 500;
